### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by R0gu3Stalk3r** [IanGallacher/JibJabNews#10]
We may need to look at other alternatives for publishing this. Unity maybe the equivalent of fishing with dynamite when all the fish are in a barrel. Maybe HTML5 or Flash or WebGL or js could be better outlets. lemme know what you think.

**Comment by IanGallacher** [comment]
I think that both of those would be fine options had we designed the game from the start to use those technologies. Best we can do at this point is export this game using unity web player.
